Resources:
  NGINXBuildComponent:
    Type: AWS::ImageBuilder::Component
    Properties: 
      Data: |
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: InstallNGINX
                action: ExecuteBash
                inputs:
                  commands:
                    - apt-get update && apt-get upgrade --yes
                    - apt-get install nginx --yes
      Name: UbuntuNGINX
      Platform: Linux
      Tags: 
        User: 'Trevor Sullivan'
      Version: 1.2.0